### ISSUE TITLE
SINGE benchmarking

### ISSUE THREAD

**Issue by agitter** [neocaleb/TENET#1]
I saw your [bioRxiv preprint](https://doi.org/10.1101/2019.12.20.884163) recently, and the work looks very interesting.

I am one of the developers of [SINGE](https://github.com/gitter-lab/SINGE) (formerly called SCINGE) and am wondering which version of the software you used and what hyperparameters you selected.  Are these details in your manuscript or supplement?  The SINGE performance was not great in your evaluation, and we'd like to diagnose what happened.  Thanks.

**Comment by agitter** [comment]
@neocaleb we recently [released ](https://github.com/gitter-lab/SINGE/releases ) version 0.4.0 of SINGE, which includes much better Docker support.  If you were using an older version of SINGE through BEELINE or not running the SINGE ensembling, we could help you run the latest version for your benchmarking.

**Comment by neocaleb** [comment]
@agitter Hi, sorry for late response. I saw this message now. And thank you for your interest in my preprint.
Yes, I run SINGE through BEELINE late of last year. So, I am not sure about the version of SINGE. If you let me know your email, I can send you the data for benchmarking.

**Comment by agitter** [comment]
@neocaleb the BEELINE authors updated the version of SINGE they include to version 0.4.0.  That would provide one way to use the newer version with your existing workflow.

However, BEELINE does not provide easy access to the ensembling we recommend when running SINGE.  Running SINGE without ensembling is likely contributing to the poor performance.

I'll close this issue, but please feel free to ask questions about SINGE if you have any.
