### ISSUE TITLE
Using TENET with real time points

### ISSUE THREAD

**Issue by iriverog** [neocaleb/TENET#10]
Hi,

I am wondering if it could be possible to use TENET with real time points rather than pseudo time information. In my case the vector of time points will only contain a few integer values that will be repeated for most cells.

Thanks for your help!
Ines

**Comment by neocaleb** [comment]
Hi,

Basically, you can apply TENET for your data with real time points. However, you need to know that TENET calculate transfer entropy values only considering discrete time point like (t=1, 2, 3, ...).

Best
Junil

**Comment by iriverog** [comment]
Hi Juni,

Thank you for your quick reply.

Ines
