### ISSUE TITLE
A few issues

### ISSUE THREAD

**Issue by hwlim** [neocaleb/TENET#3]
1. It would be better to explicitly use python3 instead of python since some computer often have python2 as default python
2. It seems like input files must be located within the current working directory. It would be convenient to allow input files in a separate folder for handling multiple different data sets.
3. openmpi dependency is not clear. at least it didn't work with openmpi3. I guess it's based on openmpi > 4.0?

**Comment by neocaleb** [comment]
Hi Lim,

Thank you for your constructive comments. I will update TENET.
