### ISSUE TITLE
a few typoes

### ISSUE THREAD

**Issue by hwlim** [neocaleb/TENET#4]
1. in makeGRNbyTF.py
Line 8:
ifile = open("GO_symbol_"+species+"_regulation_of_transcription+sequence-specific_DNA_binding_list_list.txt")
==> ifile = open("GO_symbol_"+species+"_regulation_of_transcription+sequence-specific_DNA_binding_list.txt")

NumberOfLinks=sys.argv[2]
Line 42:
fdrCutoff=float(sys.argv[1])
==> fdrCutoff=float(sys.argv[2])

2.  in makeGRNbyTFsameNumberOfLinks.py
Line 6:
ifile = open("GO_symbol_"+species+"_regulation_of_transcription+sequence-specific_DNA_binding_list_list.txt")
==> ifile = open("GO_symbol_"+species+"_regulation_of_transcription+sequence-specific_DNA_binding_list.txt")

**Comment by neocaleb** [comment]
Thank you Lim! I will correct them.
