### ISSUE TITLE
Re: example output wondering

### ISSUE THREAD

**Issue by LI90040** [neocaleb/TENET#6]
Hello, 
I am doing application research on the reconstruction of gene regulatory networks and interested in the TENET algorithm. However, when I running the example data, the result matrix in TE_result_matrix.txt is all 0 for all pairs of genes. I am wondering should this output be all 0 for the example data? (or I make the mistake in running the code). Thank you so much for your help.

**Comment by neocaleb** [comment]
Hi,
Thank you for interesting in TENET. It should not be all 0. Which version of TENET did you use? It might be fail to distribute jobs. Have you checked any error message?

**Comment by LI90040** [comment]
Hello, thank you for your reply. I used the newest version of TENET 2.3 (download the whole zip package of version 2.3) and only one error message shows: "cat: outputs/*.csv: No such file or directory" and with output matrix of all zeros. I am trying to run TENET using expression data in a csv file and pseudotime result in a text file.

**Comment by neocaleb** [comment]
Would you send me your pseudotime and expression matrix?

2021년 4월 6일 (화) 오후 11:46, LI90040 ***@***.***>님이 작성:

**Comment by LI90040** [comment]
I am just running the example provided in the TENET file (which download within the zip file
[trajectory.txt](https://github.com/neocaleb/TENET/files/6265513/trajectory.txt)
).

**Comment by LI90040** [comment]
[Archive.zip](https://github.com/neocaleb/TENET/files/6265535/Archive.zip)
Here is the full zip data that I used. I am just trying to follow the example ./TENET expression_data.csv 10 trajectory.txt cell_select.txt 1 and want to get a idea of how the output looks like but gave me all zeros. 
[TE_result_matrix.txt](https://github.com/neocaleb/TENET/files/6265540/TE_result_matrix.txt) I am not sure did I did something wrong.

**Comment by neocaleb** [comment]
I see. Have you installed openmpi (version>4.0)? Sometimes it is fail to
run python modules in the distributed threads. If you installed all the
required package, and still it doesn’t work. I will send you another
version for single core.

2021년 4월 6일 (화) 오후 11:57, LI90040 ***@***.***>님이 작성:

**Comment by LI90040** [comment]
Yes, I check my open mpi version is already 4.1.0.

**Comment by LI90040** [comment]
hel lo

**Comment by LI90040** [comment]
hello, I had double-checked all the required package, and they already at the newest version. It would be great if you can send me another version for single-core. Thank you so much for your time.  :)

**Comment by neocaleb** [comment]
Hi,

I updated my Github page. You can use TENETsinglecore following the example.
Please let me know if you have any problems. And if you got an error
message for the original version of TENET, please send it to me.

Best
Junil

2021년 4월 8일 (목) 오전 10:19, LI90040 ***@***.***>님이 작성:

**Comment by LI90040** [comment]
Thank you~ :)
